// Per-image captions for gallery techniques.
// Map: Technique -> { [basename: string]: { description?: string; year?: number|string; school?: string } }
// Edit the empty objects ({}) to add description/year/school for each photo.

const captions: Record<string, Record<string, { description?: string; year?: number|string; school?: string }>> = {
  'Pintura': {
    'pintura.jpg': {year: 2006, school: 'Liceo A-131 de Buin' },
    'pintura1.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
    'pintura2.jpg': {},
    'pintura3.jpg': {},
    'pintura4.jpg': {},
    'pintura5.jpg': {},
    'pintura6.JPG': {},
  },
  'Collage': {
    'collage.jpg': {},
    'collage1.jpg': {},
    'collage2.jpg': {},
    'collage3.jpg': {},
    'collage4.jpg': {},
    'collage5.jpg': {},
  },
  'Audiovisual': {
    'audiovisual.jpg': {},
    'audiovisual1.jpg': {},
    'audiovisual2.jpg': {},
    'audiovisual3.jpg': {},
    'audiovisual4.jpg': {},
    'audiovisual5.jpg': {},
    'audiovisual6.jpg': {},
    'audiovisual7.jpg': {},
    'audiovisual8.jpg': {},
    'audiovisual9.webp': {},
    'audiovisual10.jpg': {},
    'audiovisual11.jpg': {},
  },
  'Mosaico': {
    'mosaico.jpg': {},
    'mosaico_2.jpg': {},
    'mosaico_3.jpg': {},
    'mosaico_7.jpg': {},
    'mosaico4.jpg': {},
    'mosaico5.jpg': {},
    'mosaico6.jpg': {},
  },
  'Volumen': {
    'volumen.jpg': {},
    'volumen1.png': {},
    'volumen2.png': {},
    'volumen3.png': {},
    'volumen4.png': {},
    'volumen-geometrica.webp': {},
    'volumen-organos_1.jpg': {},
    'volumen-organos_2.jpg': {},
    'volumen-organos_3.jpg': {},
  },
  'Máscaras': {
    'mascara.jpg': {},
    'mascara1.jpg': {},
    'mascara2.jpg': {},
    'mascara3.jpg': {},
    'mascara4.jpg': {},
    'mascara5.jpg': {},
    'mascara6.jpg': {},
    'mascara7.jpg': {},
    'mascara8.jpg': {},
    'mascara9.jpg': {},
    'mascara10.jpg': {},
    'mascara12.jpg': {},
    'mascara12.png': {},
    'mascara13.jpg': {},
    'mascara14.jpg': {},
    'mascara15.jpg': {},
    'mascara16.jpg': {},
    'mascara17.jpg': {},
  },
  'Lámparas': {
    // Nota: el listado de la galería usa archivos que comienzan con "lamparas".
    'lamparas.jpg': {},
    'lamparas1.jpg': {},
    'lamparas2.jpg': {},
    'lamparas3.jpg': {},
    'lamparas4.jpg': {},
    'lamparas5.jpg': {},
    'lamparas6.jpg': {},
    'lamparas7.jpg': {},
    'lamparas8.jpg': {},
    'lamparas9.jpg': {},
    'lamparas10.jpg': {},
    'lamparas11.jpg': {},
    'lamparas12.png': {},
  },
  'Diseño': {
    'diseño.jpg': {},
    'diseño1.jpg': {},
    'diseño2-pixelart.jpg': {},
  },
  'Dibujo': {
    'dibujo.jpg': {},
    'dibujo2.jpg': {},
    'dibujo3.jpg': {},
  },
};

export default captions;
