// Per-image captions for gallery techniques.
// Map: Technique -> { [basename: string]: { description?: string; year?: number|string; school?: string } }
// Edit the empty objects ({}) to add description/year/school for each photo.

const captions: Record<string, Record<string, { description?: string; year?: number | string; school?: string }>> = {
    'Pintura': {
        'pintura.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura1.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura2.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura3.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura4.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura5.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura6.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura7.jpg': { year: 2020, school: 'Artenlaclase' },
            'pintura8.jpeg': { year: 2025, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'pintura9.jpeg': { year: 2025, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'pintura10.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura11.jpg': { year: 2021, school: 'Colegio María Griselda Valle, El Bosque' },
            'pintura12.jpg': { year: 2020, school: 'Artenlaclase' },
            'pintura13.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura14.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura15.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
    },
    'Collage': {
        'collage-arte-colaborativo-2007.jpg': { description: 'Arte colaborativo', year: 2007, school: 'Liceo A-131 de Buin' },
        'collage-creatividad-paisaje-clase-2013.jpg': { description: 'Creatividad paisaje en clase', year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'collage-materiales-reciclados-2007.jpg': { description: 'Materiales reciclados', year: 2007, school: 'Liceo A-131 de Buin' },
        'collage-materiales-reciclados-clase-2005.jpg': { description: 'Materiales reciclados en clase', year: 2005, school: 'Liceo A-131 de Buin' },
        'collage-paisaje-natural-2007.jpg': { description: 'Paisaje natural', year: 2007, school: 'Liceo A-131 de Buin' },
        'collage-paisaje-surreal-2015.jpg': { description: 'Paisaje surreal', year: 2015, school: 'Colegio Nova Terra La Florida' },
        'collage-papel-revista-composicion-2007.jpg': { description: 'Papel de revista composición', year: 2007, school: 'Liceo A-131 de Buin' },
        'collage-texturas-mixtas-arte-2017.jpg': { description: 'Texturas mixtas', year: 2017, school: 'Instituto La Salle La Florida' },
    },
    'Audiovisual': {
        'audiovisual-taller-cine-2018.jpg': { year: 2018, school: 'Instituto La Salle La Florida', description: 'Taller de cine' },
        'audiovisual-estudiante-grabando-green-screen-2015.jpg': { year: 2015, school: 'Colegio Nova Terra La Florida', description: 'Estudiante grabando con green screen' },
        'audiovisual-estudiantes-grabando-cortometraje-2018.jpg': { year: 2018, school: 'Instituto La Salle La Florida', description: 'Estudiantes grabando cortometraje' },
        'audiovisual-estudiantes-grabando-cortometraje-2015.jpg': { year: 2015, school: 'Colegio Nova Terra La Florida', description: 'Estudiantes grabando cortometraje' },
        'audiovisual-estudiantes-grabando-clip-musical-2016.jpg': { year: 2016, school: 'Colegio Altazor Puente Alto', description: 'Estudiantes grabando clip musical' },
        'audiovisual-estudiante-camarografo-iluminación-2015.jpg': { year: 2015, school: 'Colegio Nova Terra La Florida', description: 'Estudiante camarógrafo con iluminación' },
        'audiovisual-personaje-clip-musical-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Personaje de clip musical' },
        'audiovisual-clase-escenas-en-un-texto-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Clase sobre escenas en un texto' },
        'audiovisual-clase-storyboard-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Clase de storyboard' },
        'audiovisual-estudiantes-espectadores-y-equipo-produccion-2018.jpg': { year: 2018, school: 'Instituto La Salle La Florida', description: 'Estudiantes como espectadores y equipo de producción' },
        'audiovisual-grabando-tutoriales-artenlaclase-2021.jpg': { year: 2021, school: 'Artenlaclase', description: 'Grabando tutoriales educativos' },
        'audiovisual-profesor-grabando-tutorial-2020.jpg': { year: 2020, school: 'Artenlaclase', description: 'Profesor grabando tutorial' },
        'audiovisual-proyecto-interdisciplinario-plan-lector-2019.webp': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Proyecto interdisciplinario plan lector' },
        'audiovisual-storyboard-clip-musical-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Storyboard para clip musical' },
    },
    'Mosaico': {
            'mosaico.jpg':   { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico2.jpg': { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico3.jpg': { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico7.jpg': { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico4.jpg':  { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico5.jpg':  { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico6.jpg':  { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
    },
        'Volumen': {
            'volumen.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen1.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen2.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen3.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen4.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen5.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen6.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen7.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen-geometrica.webp': { year: 2018, school: 'Instituto La Salle La Florida' },
            'volumen-grafica-mapuche.heic': { year: 2024, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'volumen-grafica-mapuche-1.heic': { year: 2024, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'volumen-grafica-mapuche-2.heic': { year: 2024, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'volumen-organos_1.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'volumen-organos_2.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'volumen-organos_3.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'volumen-organos_4.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        },
        // Imágenes sueltas usadas en otras secciones
        'Otros': {
            'experiencia.webp':   { year: 2017, school: 'Instituto La Salle La Florida' },
            'experimentales.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
        },
    'Mascaras': {
            'mascara.jpg': { year: 2022, school: 'Colegio María Griselda Valle, El Bosque' },
            'mascara1.jpg': { year: 2022, school: 'Colegio María Griselda Valle, El Bosque' },
            'mascara2.jpg': { year: 2022, school: 'Colegio María Griselda Valle, El Bosque' },
            'mascara3.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara4.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara5.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara6.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara7.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara8.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara9.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara10.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara11.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara12.jpg': { year: 2012, school: 'Artenlaclase' },
            'mascara12.png': { year: 2012, school: 'Artenlaclase' },
            'mascara13.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara14.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara15.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara16.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara17.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara18.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara19.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara20.jpg': { year: 2020, school: 'Artenlaclase' },
            'mascara21.jpg': { year: 2020, school: 'Artenlaclase' },
            'mascara22.jpg': {},
            'mascara23.jpg': { year: 2020, school: 'Artenlaclase' },
            'mascara24.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara25.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
    },
    'Lamparas': {
            // Nota: el listado de la galería usa archivos que comienzan con "lamparas".
            // 'lampara.png' no se usa en la galería, pero dejamos la metadata por si se muestra en otro contexto.
            'lampara.png':  { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas1.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas2.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas3.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas4.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas5.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas6.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas7.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas8.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas9.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas10.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas11.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas12.png': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas13.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas14.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'lamparas15.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'lamparas16.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas17.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas18.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas19.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas20.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas21.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas22.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas23.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas24.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas25.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas26.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'lamparas27.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
    },
    'Diseno': {
        'diseño.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño1.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño2-pixelart.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño3.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño4.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño5.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño6.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño7.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño8.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño9.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño10.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño11.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño12.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño13.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño14.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño15.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño16.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño17.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño18.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño19.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño20.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
        'diseño21.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño22.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño23.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño24.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
    },
    'Dibujo': {
        'dibujo-actividad-clase-artes-visuales-2018.jpg': { description: 'Actividad en clase de artes visuales', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-actividad-completar-medio-rostro-2017.jpg': { description: 'Actividad completar medio rostro', year: 2017, school: 'Instituto La Salle La Florida' },
        'dibujo-autorretrato-2018.jpg': { description: 'Autorretrato', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-clase-autorretrato-estudio-2018.jpg': { description: 'Clase de autorretrato estudio', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-clase-proporcion-rostro-2018.jpg': { description: 'Clase de proporción del rostro', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-collage-ejercicios-proporcion-2018.jpg': { description: 'Collage de ejercicios de proporción', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-completando-el-rostro-2018.jpg': { description: 'Completando el rostro', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-deformando-proporciones-rostro-2018.jpg': { description: 'Deformando proporciones del rostro', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-distorsion-derformar-anatomia-rostro-2017.jpg': { description: 'Distorsión y deformación de anatomía del rostro', year: 2017, school: 'Instituto La Salle La Florida' },
        'dibujo-ejercicio-proporcion-rostro-2018.jpg': { description: 'Ejercicio de proporción del rostro', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-ejercicio-proporcion-rostro-clase-2018.jpg': { description: 'Ejercicio de proporción del rostro en clase', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-estudio-anatomia-2017.jpg': { description: 'Estudio de anatomía', year: 2017, school: 'Instituto La Salle La Florida' },
        'dibujo-grafica-mapuche-clase-2024.jpg': { description: 'Gráfica mapuche en clase', year: 2024, school: 'Liceo Municipal Pablo Neruda, Navidad' },
        'dibujo-perspectiva-un-punto-de-fuga-2018.jpg': { description: 'Perspectiva con un punto de fuga', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-practica-proporcion-rostro-2018.jpg': { description: 'Práctica de proporción del rostro', year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo-profesor-raul-rosales-2016.jpg': { description: 'Retrato del profesor Raúl Rosales', year: 2016, school: 'Colegio Altazor Puente Alto' },
        'dibujo-proyecto-autorretrato-2015.jpg': { description: 'Proyecto de autorretrato', year: 2015, school: 'Colegio Nova Terra La Florida' },
        'dibujo-proyecto-deformes-2017.jpg': { description: 'Proyecto deformes', year: 2017, school: 'Instituto La Salle La Florida' },
    },
};

export default captions;
