// Per-image captions for gallery techniques.
// Map: Technique -> { [basename: string]: { description?: string; year?: number|string; school?: string } }
// Edit the empty objects ({}) to add description/year/school for each photo.

const captions: Record<string, Record<string, { description?: string; year?: number | string; school?: string }>> = {
    'Pintura': {
        'pintura.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura1.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura2.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura3.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura4.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
        'pintura5.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura6.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura7.jpg': { year: 2020, school: 'Artenlaclase' },
            'pintura8.jpeg': { year: 2025, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'pintura9.jpeg': { year: 2025, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'pintura10.jpg': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura11.jpg': { year: 2021, school: 'Colegio María Griselda Valle, El Bosque' },
            'pintura12.jpg': { year: 2020, school: 'Artenlaclase' },
            'pintura13.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura14.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
            'pintura15.JPG': { year: 2006, school: 'Liceo A-131 de Buin' },
    },
    'Collage': {
        'collage.jpg': { year: 2007, school: 'Liceo A-131 de Buin' },
        'collage1.jpg': { year: 2007, school: 'Liceo A-131 de Buin' },
        'collage2.jpg': { year: 2007, school: 'Liceo A-131 de Buin' },
        'collage3.jpg': { year: 2007, school: 'Liceo A-131 de Buin' },
        'collage4.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'collage5.jpg': { year: 2007, school: 'Liceo A-131 de Buin' },
        // Present if available in assets
        'collage6.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'collage7.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
    },
    'Audiovisual': {
        'audiovisual-taller-cine-2018.jpg': { year: 2018, school: 'Instituto La Salle La Florida', description: 'Taller de cine' },
        'audiovisual-estudiante-grabando-green-screen-2015.jpg': { year: 2015, school: 'Colegio Nova Terra La Florida', description: 'Estudiante grabando con green screen' },
        'audiovisual-estudiantes-grabando-cortometraje-2018.jpg': { year: 2018, school: 'Instituto La Salle La Florida', description: 'Estudiantes grabando cortometraje' },
        'audiovisual-estudiantes-grabando-cortometraje-2015.jpg': { year: 2015, school: 'Colegio Nova Terra La Florida', description: 'Estudiantes grabando cortometraje' },
        'audiovisual-estudiantes-grabando-clip-musical-2016.jpg': { year: 2016, school: 'Colegio Altazor Puente Alto', description: 'Estudiantes grabando clip musical' },
        'audiovisual-estudiante-camarografo-iluminación-2015.jpg': { year: 2015, school: 'Colegio Nova Terra La Florida', description: 'Estudiante camarógrafo con iluminación' },
        'audiovisual-personaje-clip-musical-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Personaje de clip musical' },
        'audiovisual-clase-escenas-en-un-texto-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Clase sobre escenas en un texto' },
        'audiovisual-clase-storyboard-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Clase de storyboard' },
        'audiovisual-estudiantes-espectadores-y-equipo-produccion-2018.jpg': { year: 2018, school: 'Instituto La Salle La Florida', description: 'Estudiantes como espectadores y equipo de producción' },
        'audiovisual-grabando-tutoriales-artenlaclase-2021.jpg': { year: 2021, school: 'Artenlaclase', description: 'Grabando tutoriales educativos' },
        'audiovisual-profesor-grabando-tutorial-2020.jpg': { year: 2020, school: 'Artenlaclase', description: 'Profesor grabando tutorial' },
        'audiovisual-proyecto-interdisciplinario-plan-lector-2019.webp': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Proyecto interdisciplinario plan lector' },
        'audiovisual-storyboard-clip-musical-2019.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto', description: 'Storyboard para clip musical' },
    },
    'Mosaico': {
            'mosaico.jpg':   { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico2.jpg': { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico3.jpg': { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico7.jpg': { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico4.jpg':  { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico5.jpg':  { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
            'mosaico6.jpg':  { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
    },
        'Volumen': {
            'volumen.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen1.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen2.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen3.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen4.png': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen5.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen6.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen7.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'volumen-geometrica.webp': { year: 2018, school: 'Instituto La Salle La Florida' },
            'volumen-grafica-mapuche.heic': { year: 2024, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'volumen-grafica-mapuche-1.heic': { year: 2024, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'volumen-grafica-mapuche-2.heic': { year: 2024, school: 'Liceo Municipal Pablo Neruda, Navidad' },
            'volumen-organos_1.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'volumen-organos_2.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'volumen-organos_3.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'volumen-organos_4.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        },
        // Imágenes sueltas usadas en otras secciones
        'Otros': {
            'experiencia.webp':   { year: 2017, school: 'Instituto La Salle La Florida' },
            'experimentales.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
        },
    'Mascaras': {
            'mascara.jpg': { year: 2022, school: 'Colegio María Griselda Valle, El Bosque' },
            'mascara1.jpg': { year: 2022, school: 'Colegio María Griselda Valle, El Bosque' },
            'mascara2.jpg': { year: 2022, school: 'Colegio María Griselda Valle, El Bosque' },
            'mascara3.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara4.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara5.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara6.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara7.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara8.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
            'mascara9.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara10.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara11.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara12.jpg': { year: 2012, school: 'Artenlaclase' },
            'mascara12.png': { year: 2012, school: 'Artenlaclase' },
            'mascara13.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara14.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara15.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara16.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara17.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara18.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara19.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara20.jpg': { year: 2020, school: 'Artenlaclase' },
            'mascara21.jpg': { year: 2020, school: 'Artenlaclase' },
            'mascara22.jpg': {},
            'mascara23.jpg': { year: 2020, school: 'Artenlaclase' },
            'mascara24.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
            'mascara25.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
    },
    'Lamparas': {
            // Nota: el listado de la galería usa archivos que comienzan con "lamparas".
            // 'lampara.png' no se usa en la galería, pero dejamos la metadata por si se muestra en otro contexto.
            'lampara.png':  { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas1.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas2.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas3.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas4.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas5.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas6.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas7.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas8.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas9.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas10.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas11.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas12.png': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas13.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas14.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'lamparas15.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'lamparas16.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas17.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas18.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas19.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas20.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas21.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas22.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas23.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas24.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas25.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
            'lamparas26.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
            'lamparas27.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
    },
    'Diseno': {
        'diseño.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño1.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño2-pixelart.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño3.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño4.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño5.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño6.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño7.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño8.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño9.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño10.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño11.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño12.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño13.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño14.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño15.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño16.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño17.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño18.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño19.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño20.jpg': { year: 2012, school: 'Colegio King School Cordillera La Pintana' },
        'diseño21.jpg': { year: 2013, school: 'Colegio King School Cordillera La Pintana' },
        'diseño22.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'diseño23.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
        'diseño24.jpg': { year: 2019, school: 'Colegio Eyzaguirre Puente Alto' },
    },
    'Dibujo': {
        'dibujo.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        // If this file exists
        'dibujo1.jpg': {},
        'dibujo2.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo3.jpg': { year: 2024, school: 'Liceo Municipal Pablo Neruda' },
        'dibujo4.jpg': { year: 2008, school: 'Liceo A-131 de Buin' },
        'dibujo5.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo6.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo7.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo8.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo9.jpg': { year: 2016, school: 'Colegio Altazor Puente Alto' },
        'dibujo10.jpg': { year: 2011, school: 'Colegio King School Cordillera La Pintana' },
        'dibujo11.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo12.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo13.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo14.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo15.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo16.jpg': { year: 2017, school: 'Instituto La Salle La Florida' },
        'dibujo17.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
        'dibujo18.jpg': { year: 2018, school: 'Instituto La Salle La Florida' },
    },
};

export default captions;
